<?xml version="1.0" encoding="utf-8"?>
      
        <?codewarrior exportversion="1.0.1" ideversion="5.0" ?>
        <!DOCTYPE PROJECT[
          <!ELEMENT PROJECT (TARGETLIST, TARGETORDER, GROUPLIST, DESIGNLIST?, PLUGINDATALIST?)>
          <!ELEMENT TARGETLIST (TARGET+)>
          <!ELEMENT TARGET (NAME, SETTINGLIST, FILELIST?, LINKORDER?, SEGMENTLIST?, OVERLAYGROUPLIST?, SUBTARGETLIST?, SUBPROJECTLIST?, FRAMEWORKLIST?, PACKAGEACTIONSLIST?)>
          <!ELEMENT NAME (#PCDATA)>
          <!ELEMENT USERSOURCETREETYPE (#PCDATA)>
          <!ELEMENT PATH (#PCDATA)>
          <!ELEMENT FILELIST (FILE*)>
          <!ELEMENT FILE (PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?, ROOTFILEREF?, FILEKIND?, FILEFLAGS?)>
          <!ELEMENT PATHTYPE (#PCDATA)>
          <!ELEMENT PATHROOT (#PCDATA)>
          <!ELEMENT ACCESSPATH (#PCDATA)>
          <!ELEMENT PATHFORMAT (#PCDATA)>
          <!ELEMENT ROOTFILEREF (PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?)>
          <!ELEMENT FILEKIND (#PCDATA)>
          <!ELEMENT FILEFLAGS (#PCDATA)>
          <!ELEMENT FILEREF (TARGETNAME?, PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?)>
          <!ELEMENT TARGETNAME (#PCDATA)>
          <!ELEMENT SETTINGLIST ((SETTING|PANELDATA)+)>
          <!ELEMENT SETTING (NAME?, (VALUE|(SETTING+)))>
          <!ELEMENT PANELDATA (NAME, VALUE)>
          <!ELEMENT VALUE (#PCDATA)>
          <!ELEMENT LINKORDER (FILEREF*)>
          <!ELEMENT SEGMENTLIST (SEGMENT+)>
          <!ELEMENT SEGMENT (NAME, ATTRIBUTES?, FILEREF*)>
          <!ELEMENT ATTRIBUTES (#PCDATA)>
          <!ELEMENT OVERLAYGROUPLIST (OVERLAYGROUP+)>
          <!ELEMENT OVERLAYGROUP (NAME, BASEADDRESS, OVERLAY*)>
          <!ELEMENT BASEADDRESS (#PCDATA)>
          <!ELEMENT OVERLAY (NAME, FILEREF*)>
          <!ELEMENT SUBTARGETLIST (SUBTARGET+)>
          <!ELEMENT SUBTARGET (TARGETNAME, ATTRIBUTES?, FILEREF?)>
          <!ELEMENT SUBPROJECTLIST (SUBPROJECT+)>
          <!ELEMENT SUBPROJECT (FILEREF, SUBPROJECTTARGETLIST)>
          <!ELEMENT SUBPROJECTTARGETLIST (SUBPROJECTTARGET*)>
          <!ELEMENT SUBPROJECTTARGET (TARGETNAME, ATTRIBUTES?, FILEREF?)>
          <!ELEMENT FRAMEWORKLIST (FRAMEWORK+)>
          <!ELEMENT FRAMEWORK (FILEREF, DYNAMICLIBRARY?, VERSION?)>
          <!ELEMENT PACKAGEACTIONSLIST (PACKAGEACTION+)>
          <!ELEMENT PACKAGEACTION (#PCDATA)>
          <!ELEMENT LIBRARYFILE (FILEREF)>
          <!ELEMENT VERSION (#PCDATA)>
          <!ELEMENT TARGETORDER (ORDEREDTARGET|ORDEREDDESIGN)*>
          <!ELEMENT ORDEREDTARGET (NAME)>
          <!ELEMENT ORDEREDDESIGN (NAME, ORDEREDTARGET+)>
          <!ELEMENT GROUPLIST (GROUP|FILEREF)*>
          <!ELEMENT GROUP (NAME, (GROUP|FILEREF)*)>
          <!ELEMENT DESIGNLIST (DESIGN+)>
          <!ELEMENT DESIGN (NAME, DESIGNDATA)>
          <!ELEMENT DESIGNDATA (#PCDATA)>
          <!ELEMENT PLUGINDATALIST (PLUGINDATA+)>
          <!ELEMENT PLUGINDATA (NAME, VALUE)>
        ]>
      
    <PROJECT xmlns:sln="http://freescale.com/ns/beekit/solution" xmlns:tools="http://freescale.com/ns/beekit/tools" xmlns:macphy="http://freescale.com/ns/beekit/macphy" xmlns:plm="http://freescale.com/ns/beekit/plm" xmlns:nwk="http://freescale.com/ns/beekit/zigbee/beestack" xmlns:plm2="http://freescale.com/ns/beekit/smac/plm"><TARGETLIST><TARGET><NAME>MC1321XNCB</NAME><SETTINGLIST><SETTING><NAME>UserSourceTrees</NAME><VALUE /></SETTING><SETTING><NAME>AlwaysSearchUserPaths</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>InterpretDOSAndUnixPaths</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>RequireFrameworkStyleIncludes</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>SourceRelativeIncludes</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>UserSearchPaths</NAME><SETTING><SETTING><NAME>SearchPath</NAME><SETTING><NAME>Path</NAME><VALUE>lib\HC08c\LIB</VALUE></SETTING><SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING><SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING></SETTING><SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>SearchPath</NAME><SETTING><NAME>Path</NAME><VALUE /></SETTING><SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING><SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING></SETTING><SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING><SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING></SETTING></SETTING><SETTING><NAME>SystemSearchPaths</NAME><SETTING><SETTING><NAME>SearchPath</NAME><SETTING><NAME>Path</NAME><VALUE>lib\HC08c\device\INCLUDE</VALUE></SETTING><SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING><SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING></SETTING><SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>SearchPath</NAME><SETTING><NAME>Path</NAME><VALUE>lib\HC08c\device\asm_include</VALUE></SETTING><SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING><SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING></SETTING><SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>SearchPath</NAME><SETTING><NAME>Path</NAME><VALUE>lib\HC08c\INCLUDE</VALUE></SETTING><SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING><SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING></SETTING><SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>SearchPath</NAME><SETTING><NAME>Path</NAME><VALUE>help\pdf</VALUE></SETTING><SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING><SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING></SETTING><SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING></SETTING></SETTING><SETTING><NAME>MWRuntimeSettings_WorkingDirectory</NAME><VALUE /></SETTING><SETTING><NAME>MWRuntimeSettings_CommandLine</NAME><VALUE /></SETTING><SETTING><NAME>MWRuntimeSettings_HostApplication</NAME><SETTING><NAME>Path</NAME><VALUE /></SETTING><SETTING><NAME>PathFormat</NAME><VALUE>Generic</VALUE></SETTING><SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING></SETTING><SETTING><NAME>MWRuntimeSettings_EnvVars</NAME><VALUE /></SETTING><SETTING><NAME>Linker</NAME><VALUE>Linker for HC08</VALUE></SETTING><SETTING><NAME>PreLinker</NAME><VALUE /></SETTING><SETTING><NAME>PostLinker</NAME><VALUE /></SETTING><SETTING><NAME>Targetname</NAME><VALUE>MC1321XNCB</VALUE></SETTING><SETTING><NAME>OutputDirectory</NAME><SETTING><NAME>Path</NAME><VALUE>bin</VALUE></SETTING><SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING><SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING></SETTING><SETTING><NAME>SaveEntriesUsingRelativePaths</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>FileMappings</NAME><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.a08</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Assembler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_asm_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.asm</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Assembler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_asm_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.bbl</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_bbl</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.c</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Compiler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_cpp_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.c08</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Compiler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_cpp_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.cc</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Compiler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_cpp_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.cmd</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.cp</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Compiler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_cpp_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.cpp</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Compiler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_cpp_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.cxx</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Compiler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_cpp_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.dbg</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Assembler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_asm_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.equ</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Assembler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_asm_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.h</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Compiler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_cpp_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.hpp</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Compiler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_cpp_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.hxx</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Compiler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_cpp_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.inc</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Assembler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_asm_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.ini</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.lst</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_imp_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.map</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.pre</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_cpp_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.prm</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_prm</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.s</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Assembler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_asm_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.s1</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.s19</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.sgm</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Compiler for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE>mwe_cpp_HC08</VALUE></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.s19</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.txt</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.a</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Importer for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.abs</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Importer for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.elf</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Importer for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.lib</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Importer for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.o</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Importer for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.obj</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE>Importer for HC08</VALUE></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.pdf</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileExtension</NAME><VALUE>.sym</VALUE></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING></SETTING><SETTING><SETTING><NAME>FileExtension</NAME><VALUE /></SETTING><SETTING><NAME>Compiler</NAME><VALUE /></SETTING><SETTING><NAME>EditLanguage</NAME><VALUE /></SETTING><SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING></SETTING></SETTING><SETTING><NAME>CacheModDates</NAME><VALUE>true</VALUE></SETTING><SETTING><NAME>DumpBrowserInfo</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>CacheSubprojects</NAME><VALUE>true</VALUE></SETTING><SETTING><NAME>UseThirdPartyDebugger</NAME><VALUE>true</VALUE></SETTING><SETTING><NAME>BrowserGenerator</NAME><VALUE>1</VALUE></SETTING><SETTING><NAME>DebuggerAppPath</NAME><SETTING><NAME>Path</NAME><VALUE>prog\hiwave.exe</VALUE></SETTING><SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING><SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING></SETTING><SETTING><NAME>DebuggerCmdLineArgs</NAME><VALUE>%targetFilePath -W -Prod=BDM_P&amp;E_Multilink_CyclonePro.ini -instance="MC1321XNCB"</VALUE></SETTING><SETTING><NAME>DebuggerWorkingDir</NAME><SETTING><NAME>Path</NAME><VALUE /></SETTING><SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING><SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING></SETTING><SETTING><NAME>CodeCompletionPrefixFileName</NAME><VALUE /></SETTING><SETTING><NAME>CodeCompletionMacroFileName</NAME><VALUE /></SETTING><SETTING><NAME>ConsoleEncoding</NAME><VALUE>0</VALUE></SETTING><SETTING><NAME>LogSystemMessages</NAME><VALUE>true</VALUE></SETTING><SETTING><NAME>AutoTargetDLLs</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>StopAtWatchpoints</NAME><VALUE>true</VALUE></SETTING><SETTING><NAME>PauseWhileRunning</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>PauseInterval</NAME><VALUE>5</VALUE></SETTING><SETTING><NAME>PauseUIFlags</NAME><VALUE>0</VALUE></SETTING><SETTING><NAME>AltExePath</NAME><SETTING><NAME>Path</NAME><VALUE /></SETTING><SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING><SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING></SETTING><SETTING><NAME>StopAtTempBPOnLaunch</NAME><VALUE>true</VALUE></SETTING><SETTING><NAME>CacheSymbolics</NAME><VALUE>true</VALUE></SETTING><SETTING><NAME>TempBPFunctionName</NAME><VALUE>main</VALUE></SETTING><SETTING><NAME>TempBPType</NAME><VALUE>0</VALUE></SETTING><SETTING><NAME>Enabled</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>ConnectionName</NAME><VALUE /></SETTING><SETTING><NAME>DownloadPath</NAME><VALUE /></SETTING><SETTING><NAME>LaunchRemoteApp</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>RemoteAppPath</NAME><VALUE /></SETTING><SETTING><NAME>CoreID</NAME><VALUE>0</VALUE></SETTING><SETTING><NAME>JTAGClockSpeed</NAME><VALUE>8000</VALUE></SETTING><SETTING><NAME>IsMultiCore</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>OSDownload</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>UseGlobalOSDownload</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>OSDownloadConnectionName</NAME><VALUE /></SETTING><SETTING><NAME>OSDownloadPath</NAME><VALUE /></SETTING><SETTING><NAME>AltDownload</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>AltDownloadConnectionName</NAME><VALUE /></SETTING><SETTING><NAME>OtherExecutables</NAME><VALUE /></SETTING><SETTING><NAME>AnalyzerConnectionName</NAME><VALUE /></SETTING><SETTING><NAME>CustomColor1</NAME><SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING><SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING><SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING></SETTING><SETTING><NAME>CustomColor2</NAME><SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING><SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING><SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING></SETTING><SETTING><NAME>CustomColor3</NAME><SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING><SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING><SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING></SETTING><SETTING><NAME>CustomColor4</NAME><SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING><SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING><SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING></SETTING><SETTING><NAME>PE_SetFocusOnErrWindow</NAME><VALUE>true</VALUE></SETTING><SETTING><NAME>PE_AutoSaveFileBeforeCodeDesign</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>PE_AutoSave</NAME><VALUE>true</VALUE></SETTING><SETTING><NAME>PE_AutoOpenBeanInspector</NAME><VALUE>true</VALUE></SETTING><SETTING><NAME>PE_AutoConnectBean</NAME><VALUE>true</VALUE></SETTING><SETTING><NAME>PE_AssignBeanNameToPeriphery</NAME><VALUE>false</VALUE></SETTING><SETTING><NAME>PE_ShowProgress</NAME><V